#include <iostream>
using namespace std;
int main() {
    cout << "Content-type: text/html\n\n";
    cout << "<html>";
    cout << "<head><title>C++ CGI Example</title></head>";
    cout << "<body>";
    cout << "<h1>Hello from C++ CGI!</h1>";
    cout << "<p>This is a simple web page generated by a C++ program.</p>";
    cout << "</body>";
    cout << "</html>";
    return 0;
}
